---
- name: Executar criação e envio de request
  hosts: all
  become: true
  tasks:
    - name: Executar o binário createRequest
      command: ./createRequest
      args:
        chdir: /root/RequestCreator

    - name: Executar o script teste.py com python3
      command: python3 teste.py
      args:
        chdir: /root/RequestCreator/create

    - name: Executar o script sendRequest
      command: ./sendRequest
      args:
        chdir: /root/RequestCreator/create

    - name: Encontrar arquivos no diretório /root/RequestCreator/requests
      find:
        paths: /root/RequestCreator/requests
        file_type: file
      register: arquivos_encontrados

    - name: Remover arquivos encontrados
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ arquivos_encontrados.files }}"
      when: arquivos_encontrados.matched > 0
